name: Laravel Task Scheduler

on:
  schedule:
    - cron: '0 7 * * *'  # Menjalankan setiap hari pada jam 07:00 UTC
  workflow_dispatch:

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Sesuaikan dengan versi PHP yang digunakan
          extensions: mbstring, xml, mysqli

      - name: Install dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist
          npm install # Jika kamu menggunakan npm untuk frontend

      - name: Setup MySQL
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          sudo apt-get install -y mysql-server
          sudo service mysql start
          sudo mysql --version
          sudo service mysql status
          echo "DB_PASSWORD is set to: ${DB_PASSWORD}"
          sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${DB_PASSWORD}';"
          sudo mysql -u root -p${DB_PASSWORD} -e "CREATE DATABASE railway;"
          sudo mysql -u root -p${DB_PASSWORD} -e "CREATE USER 'root'@'localhost' IDENTIFIED BY '${DB_PASSWORD}';"
          sudo mysql -u root -p${DB_PASSWORD} -e "GRANT ALL PRIVILEGES ON railway.* TO 'root'@'localhost';"
          sudo mysql -u root -p${DB_PASSWORD} -e "FLUSH PRIVILEGES;"

      - name: Run migrations
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: php artisan migrate

      - name: Run Laravel scheduler
        run: php artisan schedule:run