name: Laravel Task Scheduler

on:
  schedule:
    - cron: '0 7 * * *'  # Menjalankan setiap hari pada jam 07:00 UTC

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.0' # Sesuaikan dengan versi PHP yang digunakan
          extensions: mbstring, xml

      - name: Install dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist
          npm install # Jika kamu menggunakan npm untuk frontend

      - name: Run Laravel scheduler
        run: php artisan schedule:run
